### ISSUE TITLE
Create UI Error Page

### ISSUE THREAD

**Issue by rmc3408** [iPlayed-games/frontend#10]

**Comment by rmc3408** [comment]
@iPlayed-games/devs Can someone review and approved on Mockitt ? Also , i updated Login.
https://mockitt.wondershare.com/proto/design/pb2lk019wzp82o7au

**Comment by DanielMJSilva** [comment]
@rmc3408  I don't have access. It does not open.

**Comment by rmc3408** [comment]
@rmc3408 approved

**Comment by DLittlefield81** [comment]
@rmc3408 Approved
