### ISSUE TITLE
creating branches and draft for CICD

### ISSUE THREAD

**Issue by rmc3408** [iPlayed-games/frontend#15]

**Comment by rmc3408** [comment]
**1 - branches.**

branches = environment
MAIN = production
DEVELOP = development

**Comment by rmc3408** [comment]
@iPlayed-games/devs 
Backend pull request - https://github.com/iPlayed-games/backend/pull/8
FrontEnd pull request - https://github.com/iPlayed-games/frontend/pull/17

**Comment by DanielMJSilva** [comment]
Great.
